
import { ChemicalElement } from './types';

export const ELEMENTS: ChemicalElement[] = [
  // Period 1
  { number: 1, symbol: 'H', chinese: '氢', pinyin: 'qīng', japanese: '水素', katakana: 'すいそ', english: 'Hydrogen', ipa: '/ˈhaɪdrədʒən/', category: 'reactive-nonmetal', row: 1, column: 1 },
  { number: 2, symbol: 'He', chinese: '氦', pinyin: 'hài', japanese: 'ヘリウム', katakana: 'へりうむ', english: 'Helium', ipa: '/ˈhiːliəm/', category: 'noble-gas', row: 1, column: 18 },
  
  // Period 2
  { number: 3, symbol: 'Li', chinese: '锂', pinyin: 'lǐ', japanese: 'リチウム', katakana: 'りちうむ', english: 'Lithium', ipa: '/ˈlɪθiəm/', category: 'alkali-metal', row: 2, column: 1 },
  { number: 4, symbol: 'Be', chinese: '铍', pinyin: 'pí', japanese: 'ベリリウム', katakana: 'べりりうむ', english: 'Beryllium', ipa: '/bəˈrɪliəm/', category: 'alkaline-earth-metal', row: 2, column: 2 },
  { number: 5, symbol: 'B', chinese: '硼', pinyin: 'péng', japanese: 'ホウ素', katakana: 'ほうそ', english: 'Boron', ipa: '/ˈbɔːrɒn/', category: 'metalloid', row: 2, column: 13 },
  { number: 6, symbol: 'C', chinese: '碳', pinyin: 'tàn', japanese: '炭素', katakana: 'たんそ', english: 'Carbon', ipa: '/ˈkɑːrbən/', category: 'reactive-nonmetal', row: 2, column: 14 },
  { number: 7, symbol: 'N', chinese: '氮', pinyin: 'dàn', japanese: '窒素', katakana: 'ちっそ', english: 'Nitrogen', ipa: '/ˈnaɪtrədʒən/', category: 'reactive-nonmetal', row: 2, column: 15 },
  { number: 8, symbol: 'O', chinese: '氧', pinyin: 'yǎng', japanese: '酸素', katakana: 'さんそ', english: 'Oxygen', ipa: '/ˈɒksɪdʒən/', category: 'reactive-nonmetal', row: 2, column: 16 },
  { number: 9, symbol: 'F', chinese: '氟', pinyin: 'fú', japanese: 'フッ素', katakana: 'ふっそ', english: 'Fluorine', ipa: '/ˈflʊəriːn/', category: 'halogen', row: 2, column: 17 },
  { number: 10, symbol: 'Ne', chinese: '氖', pinyin: 'nǎi', japanese: 'ネオン', katakana: 'ねおん', english: 'Neon', ipa: '/ˈniːɒn/', category: 'noble-gas', row: 2, column: 18 },

  // Period 3
  { number: 11, symbol: 'Na', chinese: '钠', pinyin: 'nà', japanese: 'ナトリウム', katakana: 'なとりうむ', english: 'Sodium', ipa: '/ˈsoʊdiəm/', category: 'alkali-metal', row: 3, column: 1 },
  { number: 12, symbol: 'Mg', chinese: '镁', pinyin: 'měi', japanese: 'マグネシウム', katakana: 'まぐねしうむ', english: 'Magnesium', ipa: '/mæɡˈniːziəm/', category: 'alkaline-earth-metal', row: 3, column: 2 },
  { number: 13, symbol: 'Al', chinese: '铝', pinyin: 'lǚ', japanese: 'アルミニウム', katakana: 'あるみにうむ', english: 'Aluminum', ipa: '/əˈluːmɪnəm/', category: 'post-transition-metal', row: 3, column: 13 },
  { number: 14, symbol: 'Si', chinese: '硅', pinyin: 'guī', japanese: 'ケイ素', katakana: 'けいそ', english: 'Silicon', ipa: '/ˈsɪlɪkən/', category: 'metalloid', row: 3, column: 14 },
  { number: 15, symbol: 'P', chinese: '磷', pinyin: 'lín', japanese: 'リン', katakana: 'りん', english: 'Phosphorus', ipa: '/ˈfɒsfərəs/', category: 'reactive-nonmetal', row: 3, column: 15 },
  { number: 16, symbol: 'S', chinese: '硫', pinyin: 'liú', japanese: '硫黄', katakana: 'いおう', english: 'Sulfur', ipa: '/ˈsʌlfər/', category: 'reactive-nonmetal', row: 3, column: 16 },
  { number: 17, symbol: 'Cl', chinese: '氯', pinyin: 'lǜ', japanese: '塩素', katakana: 'えんそ', english: 'Chlorine', ipa: '/ˈklɔːriːn/', category: 'halogen', row: 3, column: 17 },
  { number: 18, symbol: 'Ar', chinese: '氩', pinyin: 'yà', japanese: 'アルゴン', katakana: 'あるごん', english: 'Argon', ipa: '/ˈɑːrɡɒn/', category: 'noble-gas', row: 3, column: 18 },

  // Period 4
  { number: 19, symbol: 'K', chinese: '钾', pinyin: 'jiǎ', japanese: 'カリウム', katakana: 'かりうむ', english: 'Potassium', ipa: '/pəˈtæsiəm/', category: 'alkali-metal', row: 4, column: 1 },
  { number: 20, symbol: 'Ca', chinese: '钙', pinyin: 'gài', japanese: 'カルシウム', katakana: 'かるしうむ', english: 'Calcium', ipa: '/ˈkælsiəm/', category: 'alkaline-earth-metal', row: 4, column: 2 },
  { number: 21, symbol: 'Sc', chinese: '钪', pinyin: 'kàng', japanese: 'スカンジウム', katakana: 'すかんじうむ', english: 'Scandium', ipa: '/ˈskændiəm/', category: 'transition-metal', row: 4, column: 3 },
  { number: 22, symbol: 'Ti', chinese: '钛', pinyin: 'tài', japanese: 'チタン', katakana: 'ちたん', english: 'Titanium', ipa: '/taɪˈteɪniəm/', category: 'transition-metal', row: 4, column: 4 },
  { number: 23, symbol: 'V', chinese: '钒', pinyin: 'fán', japanese: 'バナジウム', katakana: 'ばなじうむ', english: 'Vanadium', ipa: '/vəˈneɪdiəm/', category: 'transition-metal', row: 4, column: 5 },
  { number: 24, symbol: 'Cr', chinese: '铬', pinyin: 'gè', japanese: 'クロム', katakana: 'くろむ', english: 'Chromium', ipa: '/ˈkroʊmiəm/', category: 'transition-metal', row: 4, column: 6 },
  { number: 25, symbol: 'Mn', chinese: '锰', pinyin: 'měng', japanese: 'マンガン', katakana: 'まんがん', english: 'Manganese', ipa: '/ˈmæŋɡəniːz/', category: 'transition-metal', row: 4, column: 7 },
  { number: 26, symbol: 'Fe', chinese: '铁', pinyin: 'tiě', japanese: '鉄', katakana: 'てつ', english: 'Iron', ipa: '/ˈaɪərn/', category: 'transition-metal', row: 4, column: 8 },
  { number: 27, symbol: 'Co', chinese: '钴', pinyin: 'gǔ', japanese: 'コバルト', katakana: 'こばると', english: 'Cobalt', ipa: '/ˈkoʊbɒlt/', category: 'transition-metal', row: 4, column: 9 },
  { number: 28, symbol: 'Ni', chinese: '镍', pinyin: 'niè', japanese: 'ニッケル', katakana: 'にっける', english: 'Nickel', ipa: '/ˈnɪkəl/', category: 'transition-metal', row: 4, column: 10 },
  { number: 29, symbol: 'Cu', chinese: '铜', pinyin: 'tóng', japanese: '銅', katakana: 'どう', english: 'Copper', ipa: '/ˈkɒpər/', category: 'transition-metal', row: 4, column: 11 },
  { number: 30, symbol: 'Zn', chinese: '锌', pinyin: 'xīn', japanese: '亜鉛', katakana: 'あえん', english: 'Zinc', ipa: '/zɪŋk/', category: 'transition-metal', row: 4, column: 12 },
  { number: 31, symbol: 'Ga', chinese: '镓', pinyin: 'jiā', japanese: 'ガリウム', katakana: 'がりうむ', english: 'Gallium', ipa: '/ˈɡæliəm/', category: 'post-transition-metal', row: 4, column: 13 },
  { number: 32, symbol: 'Ge', chinese: '锗', pinyin: 'zhě', japanese: 'ゲルマニウム', katakana: 'げるまにうむ', english: 'Germanium', ipa: '/dʒərˈmeɪniəm/', category: 'metalloid', row: 4, column: 14 },
  { number: 33, symbol: 'As', chinese: '砷', pinyin: 'shēn', japanese: 'ヒ素', katakana: 'ひそ', english: 'Arsenic', ipa: '/ˈɑːrsənɪk/', category: 'metalloid', row: 4, column: 15 },
  { number: 34, symbol: 'Se', chinese: '硒', pinyin: 'xī', japanese: 'セレン', katakana: 'せれん', english: 'Selenium', ipa: '/səˈliːniəm/', category: 'reactive-nonmetal', row: 4, column: 16 },
  { number: 35, symbol: 'Br', chinese: '溴', pinyin: 'xiù', japanese: '臭素', katakana: 'しゅうそ', english: 'Bromine', ipa: '/ˈbroʊmiːn/', category: 'halogen', row: 4, column: 17 },
  { number: 36, symbol: 'Kr', chinese: '氪', pinyin: 'kè', japanese: 'クリプトン', katakana: 'くりぷとん', english: 'Krypton', ipa: '/ˈkrɪptɒn/', category: 'noble-gas', row: 4, column: 18 },

  // Period 5
  { number: 37, symbol: 'Rb', chinese: '铷', pinyin: 'rú', japanese: 'ルビジウム', katakana: 'るびじうむ', english: 'Rubidium', ipa: '/ruːˈbɪdiəm/', category: 'alkali-metal', row: 5, column: 1 },
  { number: 38, symbol: 'Sr', chinese: '锶', pinyin: 'sī', japanese: 'ストロンチウム', katakana: 'すとろんちうむ', english: 'Strontium', ipa: '/ˈstrɒntiəm/', category: 'alkaline-earth-metal', row: 5, column: 2 },
  { number: 39, symbol: 'Y', chinese: '钇', pinyin: 'yǐ', japanese: 'イットリウム', katakana: 'いっとりうむ', english: 'Yttrium', ipa: '/ˈɪtriəm/', category: 'transition-metal', row: 5, column: 3 },
  { number: 40, symbol: 'Zr', chinese: '锆', pinyin: 'gào', japanese: 'ジルコニウム', katakana: 'じるこにうむ', english: 'Zirconium', ipa: '/zərˈkoʊniəm/', category: 'transition-metal', row: 5, column: 4 },
  { number: 41, symbol: 'Nb', chinese: '铌', pinyin: 'ní', japanese: 'ニオブ', katakana: 'におぶ', english: 'Niobium', ipa: '/naɪˈoʊbiəm/', category: 'transition-metal', row: 5, column: 5 },
  { number: 42, symbol: 'Mo', chinese: '钼', pinyin: 'mù', japanese: 'モリブデン', katakana: 'もりぶでん', english: 'Molybdenum', ipa: '/məˈlɪbdənəm/', category: 'transition-metal', row: 5, column: 6 },
  { number: 43, symbol: 'Tc', chinese: '锝', pinyin: 'dé', japanese: 'テクネチウム', katakana: 'てくねちうむ', english: 'Technetium', ipa: '/tɛkˈniːʃiəm/', category: 'transition-metal', row: 5, column: 7 },
  { number: 44, symbol: 'Ru', chinese: '钌', pinyin: 'liǎo', japanese: 'ルテニウム', katakana: 'るてにうむ', english: 'Ruthenium', ipa: '/ruːˈθiːniəm/', category: 'transition-metal', row: 5, column: 8 },
  { number: 45, symbol: 'Rh', chinese: '铑', pinyin: 'lǎo', japanese: 'ロジウム', katakana: 'ろじうむ', english: 'Rhodium', ipa: '/ˈroʊdiəm/', category: 'transition-metal', row: 5, column: 9 },
  { number: 46, symbol: 'Pd', chinese: '钯', pinyin: 'bǎ', japanese: 'パラジウム', katakana: 'ぱらじうむ', english: 'Palladium', ipa: '/pəˈleɪdiəm/', category: 'transition-metal', row: 5, column: 10 },
  { number: 47, symbol: 'Ag', chinese: '银', pinyin: 'yín', japanese: '銀', katakana: 'ぎん', english: 'Silver', ipa: '/ˈsɪlvər/', category: 'transition-metal', row: 5, column: 11 },
  { number: 48, symbol: 'Cd', chinese: '镉', pinyin: 'gé', japanese: 'カドミウム', katakana: 'かどみうむ', english: 'Cadmium', ipa: '/ˈkædmiəm/', category: 'transition-metal', row: 5, column: 12 },
  { number: 49, symbol: 'In', chinese: '铟', pinyin: 'yīn', japanese: 'インジウム', katakana: 'いんじうむ', english: 'Indium', ipa: '/ˈɪndiəm/', category: 'post-transition-metal', row: 5, column: 13 },
  { number: 50, symbol: 'Sn', chinese: '锡', pinyin: 'xī', japanese: '錫', katakana: 'すず', english: 'Tin', ipa: '/stɪn/', category: 'post-transition-metal', row: 5, column: 14 },
  { number: 51, symbol: 'Sb', chinese: '锑', pinyin: 'tī', japanese: 'アンチモン', katakana: 'あんちもん', english: 'Antimony', ipa: '/ˈæntɪmoʊni/', category: 'metalloid', row: 5, column: 15 },
  { number: 52, symbol: 'Te', chinese: '碲', pinyin: 'dì', japanese: 'テルル', katakana: 'てるる', english: 'Tellurium', ipa: '/tɛˈlʊəriəm/', category: 'metalloid', row: 5, column: 16 },
  { number: 53, symbol: 'I', chinese: '碘', pinyin: 'diǎn', japanese: 'ヨウ素', katakana: 'ようそ', english: 'Iodine', ipa: '/ˈaɪədaɪn/', category: 'halogen', row: 5, column: 17 },
  { number: 54, symbol: 'Xe', chinese: '氙', pinyin: 'xiān', japanese: 'キセノン', katakana: 'きせのん', english: 'Xenon', ipa: '/ˈziːnɒn/', category: 'noble-gas', row: 5, column: 18 },

  // Period 6
  { number: 55, symbol: 'Cs', chinese: '铯', pinyin: 'sè', japanese: 'セシウム', katakana: 'せしうむ', english: 'Cesium', ipa: '/ˈsiːziəm/', category: 'alkali-metal', row: 6, column: 1 },
  { number: 56, symbol: 'Ba', chinese: '钡', pinyin: 'bèi', japanese: 'バリウム', katakana: 'ばりうむ', english: 'Barium', ipa: '/ˈbɛəriəm/', category: 'alkaline-earth-metal', row: 6, column: 2 },
  // Lanthanides (57-71)
  { number: 57, symbol: 'La', chinese: '镧', pinyin: 'lán', japanese: 'ランタン', katakana: 'らんたん', english: 'Lanthanum', ipa: '/ˈlænθənəm/', category: 'lanthanide', row: 9, column: 4 },
  { number: 58, symbol: 'Ce', chinese: '铈', pinyin: 'shì', japanese: 'セリウム', katakana: 'せりうむ', english: 'Cerium', ipa: '/ˈsɪəriəm/', category: 'lanthanide', row: 9, column: 5 },
  { number: 59, symbol: 'Pr', chinese: '镨', pinyin: 'pǔ', japanese: 'プラセオジム', katakana: 'ぷらせおじむ', english: 'Praseodymium', ipa: '/ˌpreɪzioʊˈdɪmiəm/', category: 'lanthanide', row: 9, column: 6 },
  { number: 60, symbol: 'Nd', chinese: '钕', pinyin: 'nǚ', japanese: 'ネオジム', katakana: 'ねおじむ', english: 'Neodymium', ipa: '/ˌniːoʊˈdɪmiəm/', category: 'lanthanide', row: 9, column: 7 },
  { number: 61, symbol: 'Pm', chinese: '钷', pinyin: 'pǒ', japanese: 'プロメチウム', katakana: 'ぷろめちうむ', english: 'Promethium', ipa: '/prəˈmiːθiəm/', category: 'lanthanide', row: 9, column: 8 },
  { number: 62, symbol: 'Sm', chinese: '钐', pinyin: 'shān', japanese: 'サマリウム', katakana: 'さまりうむ', english: 'Samarium', ipa: '/səˈmɛəriəm/', category: 'lanthanide', row: 9, column: 9 },
  { number: 63, symbol: 'Eu', chinese: '铕', pinyin: 'yǒu', japanese: 'ユウロピウム', katakana: 'ゆうろぴうむ', english: 'Europium', ipa: '/jʊˈroʊpiəm/', category: 'lanthanide', row: 9, column: 10 },
  { number: 64, symbol: 'Gd', chinese: '钆', pinyin: 'gá', japanese: 'ガドリニウム', katakana: 'がどりにうむ', english: 'Gadolinium', ipa: '/ˌɡædəˈlɪniəm/', category: 'lanthanide', row: 9, column: 11 },
  { number: 65, symbol: 'Tb', chinese: '铽', pinyin: 'tè', japanese: 'テルビウム', katakana: 'てるびうむ', english: 'Terbium', ipa: '/ˈtɜːrbiəm/', category: 'lanthanide', row: 9, column: 12 },
  { number: 66, symbol: 'Dy', chinese: '镝', pinyin: 'dí', japanese: 'ジスプロシウム', katakana: 'じすぷろしうむ', english: 'Dysprosium', ipa: '/dɪsˈproʊziəm/', category: 'lanthanide', row: 9, column: 13 },
  { number: 67, symbol: 'Ho', chinese: '钬', pinyin: 'huǒ', japanese: 'ホルミウム', katakana: 'ほるみうむ', english: 'Holmium', ipa: '/ˈhoʊlmiəm/', category: 'lanthanide', row: 9, column: 14 },
  { number: 68, symbol: 'Er', chinese: '铒', pinyin: 'ěr', japanese: 'エルビウム', katakana: 'えるびうむ', english: 'Erbium', ipa: '/ˈɜːrbiəm/', category: 'lanthanide', row: 9, column: 15 },
  { number: 69, symbol: 'Tm', chinese: '铥', pinyin: 'diū', japanese: 'ツリウム', katakana: 'つりうむ', english: 'Thulium', ipa: '/ˈθjuːliəm/', category: 'lanthanide', row: 9, column: 16 },
  { number: 70, symbol: 'Yb', chinese: '镱', pinyin: 'yì', japanese: 'イッテルビウム', katakana: 'いってるびうむ', english: 'Ytterbium', ipa: '/ɪˈtɜːrbiəm/', category: 'lanthanide', row: 9, column: 17 },
  { number: 71, symbol: 'Lu', chinese: '镥', pinyin: 'lǔ', japanese: 'ルテチウム', katakana: 'るてちうむ', english: 'Lutetium', ipa: '/luːˈtiːʃiəm/', category: 'lanthanide', row: 9, column: 18 },

  { number: 72, symbol: 'Hf', chinese: '铪', pinyin: 'hā', japanese: 'ハフニウム', katakana: 'はふにうむ', english: 'Hafnium', ipa: '/ˈhæfniəm/', category: 'transition-metal', row: 6, column: 4 },
  { number: 73, symbol: 'Ta', chinese: '钽', pinyin: 'tǎn', japanese: 'タンタル', katakana: 'たんたる', english: 'Tantalum', ipa: '/ˈtæntələm/', category: 'transition-metal', row: 6, column: 5 },
  { number: 74, symbol: 'W', chinese: '钨', pinyin: 'wū', japanese: 'タングステン', katakana: 'たんぐすてん', english: 'Tungsten', ipa: '/ˈtʌŋstən/', category: 'transition-metal', row: 6, column: 6 },
  { number: 75, symbol: 'Re', chinese: '铼', pinyin: 'lái', japanese: 'レニウム', katakana: 'れにうむ', english: 'Rhenium', ipa: '/ˈriːniəm/', category: 'transition-metal', row: 6, column: 7 },
  { number: 76, symbol: 'Os', chinese: '锇', pinyin: 'é', japanese: 'オスミウム', katakana: 'おすみうむ', english: 'Osmium', ipa: '/ˈɒzmiəm/', category: 'transition-metal', row: 6, column: 8 },
  { number: 77, symbol: 'Ir', chinese: '铱', pinyin: 'yī', japanese: 'イリジウム', katakana: 'いりじうむ', english: 'Iridium', ipa: '/ɪˈrɪdiəm/', category: 'transition-metal', row: 6, column: 9 },
  { number: 78, symbol: 'Pt', chinese: '铂', pinyin: 'bó', japanese: '白金', katakana: 'はっきん', english: 'Platinum', ipa: '/ˈplætɪnəm/', category: 'transition-metal', row: 6, column: 10 },
  { number: 79, symbol: 'Au', chinese: '金', pinyin: 'jīn', japanese: '金', katakana: 'きん', english: 'Gold', ipa: '/ɡoʊld/', category: 'transition-metal', row: 6, column: 11 },
  { number: 80, symbol: 'Hg', chinese: '汞', pinyin: 'gǒng', japanese: '水銀', katakana: 'すいぎん', english: 'Mercury', ipa: '/ˈmɜːrkjəri/', category: 'transition-metal', row: 6, column: 12 },
  { number: 81, symbol: 'Tl', chinese: '铊', pinyin: 'tā', japanese: 'タリウム', katakana: 'たりうむ', english: 'Thallium', ipa: '/ˈθæliəm/', category: 'post-transition-metal', row: 6, column: 13 },
  { number: 82, symbol: 'Pb', chinese: '铅', pinyin: 'qiān', japanese: '鉛', katakana: 'なまり', english: 'Lead', ipa: '/lɛd/', category: 'post-transition-metal', row: 6, column: 14 },
  { number: 83, symbol: 'Bi', chinese: '铋', pinyin: 'bì', japanese: 'ビスマス', katakana: 'びすます', english: 'Bismuth', ipa: '/ˈbɪzməθ/', category: 'post-transition-metal', row: 6, column: 15 },
  { number: 84, symbol: 'Po', chinese: '钋', pinyin: 'pō', japanese: 'ポロニウム', katakana: 'ぽろにうむ', english: 'Polonium', ipa: '/pəˈloʊniəm/', category: 'post-transition-metal', row: 6, column: 16 },
  { number: 85, symbol: 'At', chinese: '砹', pinyin: 'ài', japanese: 'アスタチン', katakana: 'あすたちん', english: 'Astatine', ipa: '/ˈæstətiːn/', category: 'halogen', row: 6, column: 17 },
  { number: 86, symbol: 'Rn', chinese: '氡', pinyin: 'dōng', japanese: 'ラドン', katakana: 'らどん', english: 'Radon', ipa: '/ˈreɪdɒn/', category: 'noble-gas', row: 6, column: 18 },

  // Period 7
  { number: 87, symbol: 'Fr', chinese: '钫', pinyin: 'fāng', japanese: 'フランシウム', katakana: 'ふらんしうむ', english: 'Francium', ipa: '/ˈfrænsiəm/', category: 'alkali-metal', row: 7, column: 1 },
  { number: 88, symbol: 'Ra', chinese: '镭', pinyin: 'léi', japanese: 'ラジウム', katakana: 'らじうむ', english: 'Radium', ipa: '/ˈreɪdiəm/', category: 'alkaline-earth-metal', row: 7, column: 2 },
  // Actinides (89-103)
  { number: 89, symbol: 'Ac', chinese: '锕', pinyin: 'ā', japanese: 'アクチニウム', katakana: 'あくちにうむ', english: 'Actinium', ipa: '/ækˈtɪniəm/', category: 'actinide', row: 10, column: 4 },
  { number: 90, symbol: 'Th', chinese: '钍', pinyin: 'tǔ', japanese: 'トリウム', katakana: 'とりうむ', english: 'Thorium', ipa: '/ˈθɔːriəm/', category: 'actinide', row: 10, column: 5 },
  { number: 91, symbol: 'Pa', chinese: '镤', pinyin: 'pú', japanese: 'プロトアクチニウム', katakana: 'ぷろとあくちにうむ', english: 'Protactinium', ipa: '/ˌproʊtækˈtɪniəm/', category: 'actinide', row: 10, column: 6 },
  { number: 92, symbol: 'U', chinese: '铀', pinyin: 'yóu', japanese: 'ウラン', katakana: 'うらん', english: 'Uranium', ipa: '/jʊˈreɪniəm/', category: 'actinide', row: 10, column: 7 },
  { number: 93, symbol: 'Np', chinese: '镎', pinyin: 'ná', japanese: 'ネプツニウム', katakana: 'ねぷつにうむ', english: 'Neptunium', ipa: '/nɛpˈtjuːniəm/', category: 'actinide', row: 10, column: 8 },
  { number: 94, symbol: 'Pu', chinese: '钚', pinyin: 'bù', japanese: 'プルトニウム', katakana: 'ぷるとにうむ', english: 'Plutonium', ipa: '/pluːˈtoʊniəm/', category: 'actinide', row: 10, column: 9 },
  { number: 95, symbol: 'Am', chinese: '镅', pinyin: 'méi', japanese: 'アメリシウム', katakana: 'あめりしうむ', english: 'Americium', ipa: '/ˌæməˈrɪsiəm/', category: 'actinide', row: 10, column: 10 },
  { number: 96, symbol: 'Cm', chinese: '锔', pinyin: 'jū', japanese: 'キュリウム', katakana: 'きゅりうむ', english: 'Curium', ipa: '/ˈkjʊəriəm/', category: 'actinide', row: 10, column: 11 },
  { number: 97, symbol: 'Bk', chinese: '锫', pinyin: 'péi', japanese: 'バークリウム', katakana: 'ばーくりうむ', english: 'Berkelium', ipa: '/ˈbɜːrkliəm/', category: 'actinide', row: 10, column: 12 },
  { number: 98, symbol: 'Cf', chinese: '锎', pinyin: 'kāi', japanese: 'カリホルニウム', katakana: 'かりほるにうむ', english: 'Californium', ipa: '/ˌkæləˈfɔːrniəm/', category: 'actinide', row: 10, column: 13 },
  { number: 99, symbol: 'Es', chinese: '锿', pinyin: 'āi', japanese: 'アインシュタイニウム', katakana: 'あいんしゅたいにうむ', english: 'Einsteinium', ipa: '/aɪnˈstaɪniəm/', category: 'actinide', row: 10, column: 14 },
  { number: 100, symbol: 'Fm', chinese: '镄', pinyin: 'fèi', japanese: 'フェルミウム', katakana: 'ふぇるみうむ', english: 'Fermium', ipa: '/ˈfɜːrmiəm/', category: 'actinide', row: 10, column: 15 },
  { number: 101, symbol: 'Md', chinese: '钔', pinyin: 'mén', japanese: 'メンデレビウム', katakana: 'めんでれびうむ', english: 'Mendelevium', ipa: '/ˌmɛndəˈliːviəm/', category: 'actinide', row: 10, column: 16 },
  { number: 102, symbol: 'No', chinese: '锘', pinyin: 'nuò', japanese: 'ノーベリウム', katakana: 'のーべりうむ', english: 'Nobelium', ipa: '/noʊˈbɛliəm/', category: 'actinide', row: 10, column: 17 },
  { number: 103, symbol: 'Lr', chinese: '铹', pinyin: 'láo', japanese: 'ローレンシウム', katakana: 'ろーれんしうむ', english: 'Lawrencium', ipa: '/lɔːˈrɛnsiəm/', category: 'actinide', row: 10, column: 18 },

  { number: 104, symbol: 'Rf', chinese: '鑪', pinyin: 'lú', japanese: 'ラザホージウム', katakana: 'らざほーじうむ', english: 'Rutherfordium', ipa: '/ˌrʌðərˈfɔːrdiəm/', category: 'transition-metal', row: 7, column: 4 },
  { number: 105, symbol: 'Db', chinese: '𨧀', pinyin: 'dù', japanese: 'ドブニウム', katakana: 'どぶにうむ', english: 'Dubnium', ipa: '/ˈdʌbniəm/', category: 'transition-metal', row: 7, column: 5 },
  { number: 106, symbol: 'Sg', chinese: '𨭎', pinyin: 'xǐ', japanese: 'シーボーギウム', katakana: 'しーぼーぎうむ', english: 'Seaborgium', ipa: '/siːˈbɔːrɡiəm/', category: 'transition-metal', row: 7, column: 6 },
  { number: 107, symbol: 'Bh', chinese: '𨨏', pinyin: 'bō', japanese: 'ボーリウム', katakana: 'ぼーりうむ', english: 'Bohrium', ipa: '/ˈbɔːriəm/', category: 'transition-metal', row: 7, column: 7 },
  { number: 108, symbol: 'Hs', chinese: '𨭆', pinyin: 'hēi', japanese: 'ハッシウム', katakana: 'はっしうむ', english: 'Hassium', ipa: '/ˈhæsiəm/', category: 'transition-metal', row: 7, column: 8 },
  { number: 109, symbol: 'Mt', chinese: '䥑', pinyin: 'mài', japanese: 'マイトネリウム', katakana: 'まいとねりうむ', english: 'Meitnerium', ipa: '/maɪtˈnɛəriəm/', category: 'transition-metal', row: 7, column: 9 },
  { number: 110, symbol: 'Ds', chinese: '鐽', pinyin: 'dá', japanese: 'ダームスタチウム', katakana: 'だーむすたちうむ', english: 'Darmstadtium', ipa: '/ˌdɑːrmˈʃtætiəm/', category: 'transition-metal', row: 7, column: 10 },
  { number: 111, symbol: 'Rg', chinese: '錀', pinyin: 'lún', japanese: 'レントゲニウム', katakana: 'れんとげにうむ', english: 'Roentgenium', ipa: '/ˌrʌntˈɡɛniəm/', category: 'transition-metal', row: 7, column: 11 },
  { number: 112, symbol: 'Cn', chinese: '鎶', pinyin: 'gē', japanese: 'コペルニシウム', katakana: 'こぺるにしうむ', english: 'Copernicium', ipa: '/ˌkoʊpərˈnɪsiəm/', category: 'transition-metal', row: 7, column: 12 },
  { number: 113, symbol: 'Nh', chinese: '鉨', pinyin: 'nǐ', japanese: 'ニホニウム', katakana: 'にほにうむ', english: 'Nihonium', ipa: '/niˈhoʊniəm/', category: 'post-transition-metal', row: 7, column: 13 },
  { number: 114, symbol: 'Fl', chinese: '鈇', pinyin: 'fū', japanese: 'フレロビウム', katakana: 'ふれろびうむ', english: 'Flerovium', ipa: '/flɛˈroʊviəm/', category: 'post-transition-metal', row: 7, column: 14 },
  { number: 115, symbol: 'Mc', chinese: '镆', pinyin: 'mò', japanese: 'モスコビウム', katakana: 'もすこびうむ', english: 'Moscovium', ipa: '/mɒˈskoʊviəm/', category: 'post-transition-metal', row: 7, column: 15 },
  { number: 116, symbol: 'Lv', chinese: '鉝', pinyin: 'lì', japanese: 'リバモリウム', katakana: 'りばもりうむ', english: 'Livermorium', ipa: '/ˌlɪvərˈmɔːriəm/', category: 'post-transition-metal', row: 7, column: 16 },
  { number: 117, symbol: 'Ts', chinese: '鿬', pinyin: 'tián', japanese: 'テネシン', katakana: 'てねしん', english: 'Tennessine', ipa: '/ˈtɛnəsiːn/', category: 'halogen', row: 7, column: 17 },
  { number: 118, symbol: 'Og', chinese: '鿫', pinyin: 'ào', japanese: 'オガネソン', katakana: 'おがねそん', english: 'Oganesson', ipa: '/ˌoʊɡəˈnɛsɒn/', category: 'noble-gas', row: 7, column: 18 }
];
